### ISSUE TITLE
View/Type individual entries inputs entry twice

### ISSUE THREAD

**Issue by marcosrdac** [firecat53/keepmenu#44]
Hello! I'm using Arch Linux and installed keepmenu from AUR. Standard inserting ("username\tpassword") is working fine, but when I try to type individual entries with keepmenu, they are input twice.

I recently formated my system (and I'm still using Arch), but the problem persists (it has never worked well for me).

Am I missing something?

By the way, thank you, It's nice that I can access my password in the way you've implemented keepmenu!

**Comment by firecat53** [comment]
Have you tried using xdotool instead of the default? What WM/DE? I'm also using Arch with i3 and am not seeing the same issue.

**Comment by marcosrdac** [comment]
Yes, I've installed xdotool. I've also put in "config.ini" the line:

```
type_library = xdotool
```

because my name has diacritics and keepmenu warned me to do that (the character "ã" was not being typed. But even after xdotool is installed (via pacman), this message continues to appear, and the "ã" continues not being typed.

Maybe xdotool is not being found? Thats odd :o

Answering your question, I'm using i3-gaps as my WM.

**Comment by marcosrdac** [comment]
No... I'm capable of running xdotool commands, so the program is installed.

**Comment by asimonen** [comment]
I was having exactly the same problem with xdotool. I believe #45 should fix it.

**Comment by marcosrdac** [comment]
Thank you, @asimonen , @firecat53 ! It's working now! I mean, the entries are not being typed twice :)

The only thing now is that the characters with diacrytics are still not being typed.

**Comment by marcosrdac** [comment]
I don't know what happened but... Everything is working perfectly now! Thank you guys!
