### ISSUE TITLE
hide_groups feature broken on fresh install

### ISSUE THREAD

**Issue by noerw** [firecat53/keepmenu#74]
When setting `hide_groups` in config, a broken codepath is entered.

```
Process DmenuRunner-2:
Traceback (most recent call last):
  File "/home/norwin/.local/bin/keepmenu", line 1425, in <module>
    MANAGER = client()
  File "/home/norwin/.local/bin/keepmenu", line 1234, in client
    mgr.connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 522, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/norwin/.local/bin/keepmenu", line 1269, in run
    self.dmenu_run()
  File "/home/norwin/.local/bin/keepmenu", line 1322, in dmenu_run
    sel = view_all_entries(options, [i for i in self.kpo.entries if not
  File "/home/norwin/.local/bin/keepmenu", line 1323, in <listcomp>
    any(j in i.path.rstrip(i.title) for
  File "/home/norwin/.local/bin/keepmenu", line 1323, in <genexpr>
    any(j in i.path.rstrip(i.title) for
AttributeError: 'list' object has no attribute 'rstrip'
```

Maybe the pykeepass API has changed? It returns `i.path` as a list, not as a string for me.

edit: I installed via pip:
```
Collecting keepmenu
  Downloading keepmenu-0.6.1-py3-none-any.whl (48 kB)
Requirement already satisfied: PyUserInput in /usr/lib/python3.9/site-packages (from keepmenu) (0.1.11)
Requirement already satisfied: pykeepass in /usr/lib/python3.9/site-packages (from keepmenu) (4.0.0)
Requirement already satisfied: argon2-cffi in /usr/lib/python3.9/site-packages (from pykeepass->keepmenu) (20.1.0)
Requirement already satisfied: construct==2.10.54 in /usr/lib/python3.9/site-packages (from pykeepass->keepmenu) (2.10.54)
Requirement already satisfied: pycryptodomex>=3.6.2 in /usr/lib/python3.9/site-packages (from pykeepass->keepmenu) (3.10.1)
Requirement already satisfied: python-dateutil in /usr/lib/python3.9/site-packages (from pykeepass->keepmenu) (2.8.1)
Requirement already satisfied: future in /usr/lib/python3.9/site-packages (from pykeepass->keepmenu) (0.18.2)
Requirement already satisfied: lxml in /usr/lib/python3.9/site-packages (from pykeepass->keepmenu) (4.6.2)
Requirement already satisfied: cffi>=1.0.0 in /usr/lib/python3.9/site-packages (from argon2-cffi->pykeepass->keepmenu) (1.14.5)
Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from argon2-cffi->pykeepass->keepmenu) (1.15.0)
Requirement already satisfied: pycparser in /usr/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->pykeepass->keepmenu) (2.20)
Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from argon2-cffi->pykeepass->keepmenu) (1.15.0)
Requirement already satisfied: python-xlib in /usr/lib/python3.9/site-packages (from PyUserInput->keepmenu) (0.29)
Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from argon2-cffi->pykeepass->keepmenu) (1.15.0)
Installing collected packages: keepmenu
Successfully installed keepmenu-0.6.1
```

**Comment by noerw** [comment]
Also related, when viewing a single item detail:

```
Process DmenuRunner-2:
Traceback (most recent call last):
  File "/home/hq/.local/bin/keepmenu", line 1421, in <module>
    MANAGER = client()
  File "/home/hq/.local/bin/keepmenu", line 1234, in client
    mgr.connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 522, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hq/.local/bin/keepmenu", line 1269, in run
    self.dmenu_run()
  File "/home/hq/.local/bin/keepmenu", line 1333, in dmenu_run
    text = view_entry(entry)
  File "/home/hq/.local/bin/keepmenu", line 1075, in view_entry
    kp_entries_b = "\n".join(fields).encode(ENC)
TypeError: sequence item 0: expected str instance, list found
^CTraceback (most recent call last):
  File "/home/hq/.local/bin/keepmenu", line 1421, in <module>
    MANAGER = client()
  File "/home/hq/.local/bin/keepmenu", line 1234, in client
    mgr.connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 522, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hq/.local/bin/keepmenu", line 1425, in <module>
    run()
  File "/home/hq/.local/bin/keepmenu", line 1411, in run
    server.join()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Server-1:
Traceback (most recent call last):
  File "/home/hq/.local/bin/keepmenu", line 1421, in <module>
    MANAGER = client()
  File "/home/hq/.local/bin/keepmenu", line 1234, in client
    mgr.connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 522, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hq/.local/bin/keepmenu", line 1389, in run
    self.kill_flag.wait()
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt
```

**Comment by firecat53** [comment]
I just released 0.6.5. Please give this a try and see if it fixes these issues. Thanks!

**Comment by noerw** [comment]
The bug is still present in 0.6.5. Are you sure you posted to the right issue? I see no changes regarding `i.path` in recent commits

**Comment by firecat53** [comment]
There was a breaking change in pykeepass when they released 4.0.0. Until I decide whether to support 3.2.x and/or 4.x, you can install pykeepass 3.2.x.

**Comment by firecat53** [comment]
Ok, give the develop branch a try. This requires pykeepass >= 4.0.0, but should fix the issue you are seeing.

**Comment by firecat53** [comment]
I'm pretty sure this is fixed with keepmenu 1.0.0 and pykeepass 4.0.0. Make sure you upgrade pykeepass `pip install --user -U pykeepass`. Closing, but please reopen or open another issue if it's still broken for you.
