### ISSUE TITLE
Rofi 1.7.0

### ISSUE THREAD

**Issue by RaitaroH** [firecat53/keepmenu#89]
As of rofi 1.7.0 the script doesn't work anymore. After typing any password, the script breaks. 

Steps to reproduce:
1. run `$ keepmenu`
2. type any password in the rofi window that just appeared
3. rofi now stops working and throws the following error:
```
Rofi is unsure what to show.
Please specify the mode you want to show.

rofi -show {mode}
```

The command I use in the config.ini is this, which worked fine before rofi update.
```
[dmenu]
dmenu_command = rofi -dmenu -theme green
```

Also it used to be you could use -width and -height flags, but not anymore.

**Comment by firecat53** [comment]
Since Rofi has moved their options mostly into theming, I think I'm going to
remove all support for -l, -width and -height from keepmenu and require peopel
using Rofi to set those in a theme file. I don't see an easy way to keep all the
various options straight between Rofi versions with a bunch of hacky
workarounds. I'd rather not break keepmenu for users on distros that use older
versions of Rofi.

Working on it! Thanks for the report.

**Comment by firecat53** [comment]
This should be fixed with the latest commit. Let me know if it works for you!

**Comment by RaitaroH** [comment]
I just reinstalled over the AUR. I am still having the same problem. I can tell you that the theme I am using works on it's own. Without a theme specified I still get the same problem.

**Comment by firecat53** [comment]
Can you please show me your config.ini when it doesn't work? Also, how did you reinstall? I'm not sure what you meant by "over the AUR". Make sure you completely uninstall previous versions first.

**Comment by firecat53** [comment]
I just tried this on a fresh Arch VM and I'm not seeing the same error. I strongly suspect you have an old version of keepmenu installed, perhaps in ~/.local/bin and/or ~/.local/lib/python3.9/site-packages. This is the most common cause of seeing behavior from old versions of applications/libraries. I've done it myself many times!

I also notice that you're using the old format for config.ini. Check the options as some have changed! `rofi_obscure`->`obscure` and the color definitions under `[dmenu_passphrase]` are now consolidated to `obscure_color`. You don't need to pass the `-dmenu` flag as it's added automatically, but it won't hurt anything (I've checked). Check all your options in config.ini.example.

**Comment by RaitaroH** [comment]
Hmmm, really strange. I fixed the config, but still the same, even with just dmenu_command and database_1 entries only.
You were right, there was some lingering keepmenu under site-packages so I removed those.
I even uninstalled keepmenu too and used the cloned repo version instead. Still I get the rofi issue. With dmenu it works fine.

Anyhow if you have no clue what is going on you may leave this open or close it I suppose.

**Comment by firecat53** [comment]
I'd love to see it working for you...and make sure there's not a bug that I can't see!

Try this: 

1. Completely uninstall keepmenu.  `find ~/ -iname '*keepmenu*` and delete all references to keepmenu. Also `sudo find /usr/ -iname '*keepmenu*'` (and /bin/) to make sure there aren't any relics to delete or uninstall. `rm -r ~/.config/keepmenu`
2. `git clone https://github.com/firecat53/keepmenu`
3. `cd keepmenu`
4. `python setup.py install --user`
5. Run keepmenu, and enter path to .kdbx and password/keyfile.

Hopefully that works for you!

**Comment by RaitaroH** [comment]
@firecat53 I found the problem. According to [this page](https://github.com/davatorium/rofi/wiki/Configuring-Rofi):
> From 1.7.0 the old configuration format is no longer supported and the -upgrade-config option is no longer available.

So in short there was something small in my config file for rofi itself, that somehow did not break rofi everywhere, but only for keepmenu, which made me think maybe the problem is with keepmenu. Anyhow, I have moved to the new config and now keepmenu works.
Thank you for the help.
